### ISSUE TITLE
Getting incorrect shape of input array while running the program

### ISSUE THREAD

**Issue by Nisshanthni** [anandhkishan/Handwritten-Character-Recognition-using-CNN#1]
ValueError: Cannot feed value of shape (112800, 47) for Tensor 'Placeholder_1:0'
, which has shape '(?, 59)'

**Comment by anandhkishan** [comment]
Actually I have added twelve more labels of my own dataset for prediction. You can see that in emnist-cnn-model.ipynb(Adding new dataset section). So the placeholder value will be 59. If you are using 47 labels as in EMNIST just change the shape to 47.
